CREATE DATABASE DVC6;

USE DVC6;
CREATE TABLE HOSPITAL (
  IdHOSPITAL INT IDENTITY(1,1) PRIMARY KEY,
  NOME_FANTASIA VARCHAR(100),
  CNPJ VARCHAR(18),
  EMAIL VARCHAR(30),
  SENHA VARCHAR(30),
  TELEFONE VARCHAR(15),
  CEP CHAR(8),
  NUMERO INT,
  SITE VARCHAR(45)
  );

CREATE TABLE USUARIO (
  IdUSUARIO INT IDENTITY(1,1) PRIMARY KEY,
  NOME_USUARIO VARCHAR(45),
  SENHA VARCHAR(45),
  EMAIL VARCHAR(45),
  TIPO VARCHAR(45),
  CARGO VARCHAR(30),
  fKHOSPITAL INT,
  CONSTRAINT fkHOSPITAL FOREIGN KEY (fkHOSPITAL) REFERENCES HOSPITAL (IdHOSPITAL)
);

CREATE TABLE PRE_CHECK_IN (
  idPRE_CHECK_IN INT IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(45),
  CPF VARCHAR(14),
  RG VARCHAR(12),
  IDADE INT,
  EMAIL VARCHAR(45),
  DATA_CADASTRO DATETIME,
  fkHOSPITAL INT,
  CONSTRAINT fkHOSPITAL_PRE FOREIGN KEY (fkHOSPITAL) REFERENCES HOSPITAL (IdHOSPITAL)
  );

CREATE TABLE TOTEM (
  idTOTEM INT IDENTITY(1,1) PRIMARY KEY,
  LOCALIZAÇÃO VARCHAR(45),
  NOME_MAQUINA VARCHAR(45),
  STATUS_ATUAL VARCHAR(5),
  fkHOSPITAL INT,
  CONSTRAINT fkHOSPITAL_TOTEM FOREIGN KEY (fkHOSPITAL) REFERENCES HOSPITAL (idHOSPITAL)
  );

CREATE TABLE COMPONENTE (
  idCOMPONENTE INT IDENTITY(1,1) PRIMARY KEY,
  nomeComponente VARCHAR(45),
  medidaComponente VARCHAR(20),
  TotalComponente INT,
  fkSERVIDOR INT,
  CONSTRAINT fkSERVIDOR FOREIGN KEY (fkSERVIDOR) REFERENCES TOTEM (idTOTEM)
  );

CREATE TABLE LEITURA (
  idLEITURA INT IDENTITY(1,1) PRIMARY KEY,
  DATA_HORA_ATUAL DATETIME,
  CONSUMO DECIMAL(10,2),
  fkCOMPONENTE INT,
  CONSTRAINT fkCOMPONENTE FOREIGN KEY (fkCOMPONENTE) REFERENCES COMPONENTE (idCOMPONENTE)
  );


  CREATE TABLE NIVEL_INCIDENTE(
	idNIVEL_INCIDENTE INT IDENTITY(1,1) PRIMARY KEY,
	nivelIncidente VARCHAR(20),
	descricao VARCHAR(100)
  );
  
CREATE TABLE INCIDENTE(
	idINCIDENTE INT IDENTITY(1,1) PRIMARY KEY,
	DATAINCIDENTE DATETIME,
	FkUSUARIO INT
	CONSTRAINT fkClienteIncidente FOREIGN KEY(FkUSUARIO) REFERENCES USUARIO (IDUSUARIO),
	FkNIVEL INT
	CONSTRAINT fkNIVEL FOREIGN KEY(FkNIVEL) REFERENCES NIVEL_INCIDENTE(idNIVEL_INCIDENTE)
  );

  CREATE TABLE FEEDBACK(
	idFEEDBACK INT IDENTITY(1,1) PRIMARY KEY,
	NOTA INT,
	TEXTO VARCHAR(100),
	dtHora DATETIME,
	FkUSUARIO INT
	CONSTRAINT fkClientefeedback FOREIGN KEY(FkUSUARIO) REFERENCES USUARIO (IDUSUARIO),
  );
